### ISSUE TITLE
Quark Issue

### ISSUE THREAD

**Issue by mjsyts** [spluta/Maths#1]
Hey Sam,

No idea why this is happening and I'm also pretty new to coding in general, so I apologize in advance if this is just some lack of understanding on my part.
When I added the Maths Quark and tried to use it after recompiling the class library, the server threw an error about the UGens not being installed. They were all showing in the quarks list and in the SuperCollider downloaded quarks folder, but they wouldn't work.
I downloaded the .zip file and put it in the extensions folder/got rid of the one in the quarks folder, and it worked but there may be an issue with the quark. SuperCollider would show the arguments for each UGen and show the classes for Maths in the quarks window, but on evaluation, they would fail, which I thought was odd.

**Comment by spluta** [comment]
Ack. The reason it is happening is because SC won’t load .scx files that aren’t in the Extensions folder and quarks download to a folder just outside the Extensions folder. Sorry, I never installed via the Quarks system on my computer, since it is where I am compiling the binary, and for some reason I thought this worked (though I probably knew it didn’t and was in denial).

Is there a general solution for this or a way to change where SC searches for scx files on compilation? It used to be that SC wouldn’t load classes outside the Extensions folder…so why not UGen binaries? It seems like Christof and I have had a number of back and forths about whether or not you can distribute UGens in quarks…and this is probably the reason you shouldn’t. But what would need to change for SC to look in all the “include” directories for scx files? It can’t be that difficult.

BTW - an update to the Maths is coming soon.

Sam

**Comment by mjsyts** [comment]
Putting the .zip from GitHub in the extensions folder works.
Installing the quark and recompiling classes will throw the error message on evaluation, but you can see the arguments for each UGen and access the help file with the quark installed.
Closing SuperCollider and moving the downloaded Maths quark folder into the extensions folder works.
Agreed, there should be a simple workaround for this...
